# Pod count.
min_replicas: 1
max_replicas: 1
# Quotas. Consider the replica count when setting it.
cpu_request: 60m
cpu_limit: 300m
memory_request: 760Mi
memory_limit: 850Mi

# Docker Repository path.
image:
  #version: latest
  version: latest

serviceName: "${service.name}"
infraName: "${infra.name}"
environment: "${env.name}"
namespace: "${infra.kubernetes.namespace}"

tool_stack_id: "468a05ae-3de4-4fb6-916d-5673b8505152"
profile: "${infra.name}"
isMockEnable: "${serviceVariable.isMockEnable}"

jaasconfig: "${serviceVariable.jaasconfig}"
jksPassword: "${serviceVariable.jksPassword}"

artifact_management:
  username: "${serviceVariable.artifactUsername}"
  password: "${serviceVariable.artifactPassword}"

releasenumber: ${workflow.releaseNo}

# Env variables injected into the pod.
environment_variables:
#  - name: Hello
#    value: World

# Scaling.
service_port: 80
container_port: 8080

# Health check spec.
health_check:
  liveness:
    initialDelaySeconds: 240
    httpGet:
      scheme: HTTP
      path: /actuator/health
      port: 8080
    httpGet:
      scheme: HTTP
      path: /actuator/info
      port: 8080
    timeoutSeconds: 5

  readiness:
    initialDelaySeconds: 240
    httpGet:
      scheme: HTTP
      path: /actuator/health
      port: 8080
    timeoutSeconds: 5
